name: Diagnostic format output

on:
  push:

jobs:
  format-diagnostic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install formatter
        run: sudo apt-get install -y python3 clang-format-14 clang-tidy-14
      - name: Run formatter and print diff
        run: |
          python3 format.py -j 1
          echo '--- FORMAT DIFF ---'
          git diff -- src/code/multiverse.c
          echo '--- ALL MODIFIED FILES ---'
          git status --short
